In [1]:
import pandas as pd

In [2]:
generaldf = pd.read_csv("../data/original_1_car_pricing.csv") # Data original
generaldf

,index,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,...,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,...,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,...,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,...,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,...,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,...,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,...,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,...,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,...,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,...,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,...,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [3]:
df = generaldf.sample(50000, random_state=50000) # Muestras a utilizar del total de datos

# Remplazo de datos NULL

1. Columnas categóricas y numéricas
    - Columnas categoricas, datos NULL de la columnas reemplazados por la moda
    - Columnas numéricas, datos NULL de la columnas reemplazados por la mediana

In [4]:
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

num_cols = df.select_dtypes(include='number').columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

C:\Users\tomas\AppData\Local\Temp\ipykernel_22612\1445441163.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

2. Limpieza de Año de registro
    - Años con outliners en años inexistentes o erroneos

In [5]:
mean_year = df.loc[
    (df['yearOfRegistration'] >= 1955) & 
    (df['yearOfRegistration'] <= 2019),
    'yearOfRegistration'
].mean()

df.loc[
    (df['yearOfRegistration'] < 1955) | 
    (df['yearOfRegistration'] > 2019),
    'yearOfRegistration'
] = mean_year

df['yearOfRegistration'] = df['yearOfRegistration'].astype(int)

print("Año de registro:")
print("Min:", df['yearOfRegistration'].min())
print("Max:", df['yearOfRegistration'].max())

Año de registro:
Min: 1955
Max: 2019

C:\Users\tomas\AppData\Local\Temp\ipykernel_22612\3866847155.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2003.4191830196235' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[

3. Limpieza de Precio
    - Reducción forzada de outliners, ya que eran pocos
    - Pasado de float a int

In [6]:
mean_price = df.loc[
    (df['price'] >= 500) & 
    (df['price'] <= 200000),
    'price'
].mean()

df.loc[
    (df['price'] < 500) | 
    (df['price'] > 200000),
    'price'
] = mean_price

df['price'] = df['price'].astype(int)

print("\nPrecio:")
print("Min:", df['price'].min())
print("Max:", df['price'].max())

Precio:
Min: 500
Max: 197000

C:\Users\tomas\AppData\Local\Temp\ipykernel_22612\3189082375.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '6315.361748754843' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[

4. Limpieza de Top 10 Marcas
    - Demás marcas cambiadas a "Other"

In [7]:
top_brands = df['brand'].value_counts().head(10).index
df.loc[~df['brand'].isin(top_brands), 'brand'] = 'Other'

print("\nMarcas:")
print(df['brand'].value_counts())

Marcas:
brand
volkswagen       10631
Other             9729
bmw               5439
opel              5367
mercedes_benz     4877
audi              4455
ford              3363
renault           2475
peugeot           1456
fiat              1240
seat               968
Name: count, dtype: int64

# Verificación de NULLS y su respectiva integridad

In [8]:
# Verificacion de NULL
df.isna().sum()/df.shape[0]*100

index                  0.0
dateCrawled            0.0
name                   0.0
seller                 0.0
offerType              0.0
price                  0.0
abtest                 0.0
vehicleType            0.0
yearOfRegistration     0.0
gearbox                0.0
powerPS                0.0
model                  0.0
kilometer              0.0
monthOfRegistration    0.0
fuelType               0.0
brand                  0.0
notRepairedDamage      0.0
dateCreated            0.0
nrOfPictures           0.0
postalCode             0.0
lastSeen               0.0
dtype: float64

# Detección de colunmas innecesarias para el análisis

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 293842 to 341942
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   index                50000 non-null  int64
 1   dateCrawled          50000 non-null  object
 2   name                 50000 non-null  object
 3   seller               50000 non-null  object
 4   offerType            50000 non-null  object
 5   price                50000 non-null  int32
 6   abtest               50000 non-null  object
 7   vehicleType          50000 non-null  object
 8   yearOfRegistration   50000 non-null  int32
 9   gearbox              50000 non-null  object
 10  powerPS              50000 non-null  int64
 11  model                50000 non-null  object
 12  kilometer            50000 non-null  int64
 13  monthOfRegistration  50000 non-null  int64
 14  fuelType             50000 non-null  object
 15  brand                50000 non-null  object
 16  notRepairedDamage    50000 non-null  object
 17  dateCreated          50000 non-null  object
 18  nrOfPictures         50000 non-null  int64
 19  postalCode           50000 non-null  int64
 20  lastSeen             50000 non-null  object
dtypes: int32(2), int64(6), object(13)
memory usage: 8.0+ MB

1. Columnas numéricas irrelevantes detectadas y eliminadas

In [10]:
df.describe()

,index,price,yearOfRegistration,powerPS,kilometer,monthOfRegistration,nrOfPictures,postalCode
count,50000.00000,50000.000000,50000.000000,50000.00000,50000.000000,50000.00000,50000.0,50000.000000
mean,185433.44100,6315.326840,2003.418680,115.68854,125510.500000,5.74172,0.0,50784.474400
std,107344.49796,8281.921478,7.513713,189.12424,40298.366827,3.70646,0.0,25804.966716
min,0.00000,500.000000,1955.000000,0.00000,5000.000000,0.00000,0.0,1067.000000
25%,92112.75000,1699.000000,1999.000000,70.00000,125000.000000,3.00000,0.0,30539.000000
50%,185604.00000,4000.000000,2003.000000,105.00000,150000.000000,6.00000,0.0,49681.000000
75%,278194.75000,7190.000000,2008.000000,150.00000,150000.000000,9.00000,0.0,71404.000000
max,371520.00000,197000.000000,2019.000000,20000.00000,150000.000000,12.00000,0.0,99998.000000

In [11]:
df1 = df.drop(columns=["nrOfPictures", "monthOfRegistration", "postalCode", "index"])

2. Columnas categóricas irrelevantes detectadas y eliminadas

In [12]:
df.describe(include='object')

,dateCrawled,name,seller,offerType,abtest,vehicleType,gearbox,model,fuelType,brand,notRepairedDamage,dateCreated,lastSeen
count,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000
unique,48141,38815,1,2,2,8,2,247,7,11,2,70,39524
top,2016-03-28 15:43:09,Ford_Fiesta,privat,Angebot,test,limousine,manuell,golf,benzin,volkswagen,nein,2016-04-03 00:00:00,2016-04-06 08:44:25
freq,3,85,50000,49999,26023,18033,39562,6779,34504,10631,45069,1991,7

In [13]:
df2 = df1.drop(columns=["name", "seller", "offerType", "dateCrawled", "abtest", "dateCreated", "lastSeen"])

# Almacenamiento del Data Frame con datos normalizados

In [14]:
df2.reset_index(drop=True, inplace=True)
df2.to_csv("../data/1_preprocessing_1_car_pricing.csv", index=False)