In [8]:
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_regression

In [9]:
df = pd.read_csv("../data/2_discovery_1_car_pricing.csv")
df

,price,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,fuelType,brand,notRepairedDamage
0,6315,limousine,2000,manuell,0,80,5000,benzin,audi,nein
1,1900,kleinwagen,2003,manuell,52,matiz,70000,benzin,Other,nein
2,6000,limousine,2010,manuell,105,golf,150000,diesel,volkswagen,nein
3,10499,kombi,2008,automatik,110,clubman,100000,diesel,Other,nein
4,5500,kleinwagen,2010,automatik,54,fortwo,125000,diesel,Other,nein
...,...,...,...,...,...,...,...,...,...,...
49995,2500,limousine,1998,manuell,90,golf,150000,diesel,volkswagen,nein
49996,650,limousine,2000,manuell,107,megane,150000,benzin,renault,nein
49997,1399,limousine,2002,manuell,101,golf,150000,benzin,volkswagen,nein
49998,7450,bus,2011,manuell,90,andere,90000,diesel,Other,nein
49999,6500,bus,2009,manuell,200,transit,150000,diesel,ford,nein

# TRANSFORMACION DE COLUMNAS TYPE OBJECT A INT64
Cambios con ONE-HOT en variables importantes para el modelo:
1. gearbox
2. model
3. fuelType
4. brand
5. notRepairedDamage

In [10]:
df_encoded = pd.get_dummies(df, drop_first=True)

bool_cols = df_encoded.select_dtypes(include="bool").columns
df_encoded[bool_cols] = df_encoded[bool_cols].astype(int)

df_encoded

,price,yearOfRegistration,powerPS,kilometer,vehicleType_bus,vehicleType_cabrio,vehicleType_coupe,vehicleType_kleinwagen,vehicleType_kombi,vehicleType_limousine,...,brand_bmw,brand_fiat,brand_ford,brand_mercedes_benz,brand_opel,brand_peugeot,brand_renault,brand_seat,brand_volkswagen,notRepairedDamage_nein
0,6315,2000,0,5000,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
1,1900,2003,52,70000,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2,6000,2010,105,150000,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,1
3,10499,2008,110,100000,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
4,5500,2010,54,125000,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2500,1998,90,150000,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,1
49996,650,2000,107,150000,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
49997,1399,2002,101,150000,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,1
49998,7450,2011,90,90000,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
49999,6500,2009,200,150000,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [11]:
X = df_encoded.drop(columns=["price"])
y = df_encoded["price"]

selector = SelectKBest(score_func=f_regression, k=5)
X_new = selector.fit_transform(X, y)

selected_features = X.columns[selector.get_support()]
print("Variables seleccionadas:", selected_features)

df_selected = pd.DataFrame(X_new, columns=selected_features)
df_selected["price"] = y.values

df_encoded.to_csv("../data/4_codification_1_car_pricing.csv", index=False)
df_selected

Variables seleccionadas: Index(['yearOfRegistration', 'powerPS', 'kilometer', 'gearbox_manuell',
       'model_911'],
      dtype='object')

,yearOfRegistration,powerPS,kilometer,gearbox_manuell,model_911,price
0,2000,0,5000,1,0,6315
1,2003,52,70000,1,0,1900
2,2010,105,150000,1,0,6000
3,2008,110,100000,0,0,10499
4,2010,54,125000,0,0,5500
...,...,...,...,...,...,...
49995,1998,90,150000,1,0,2500
49996,2000,107,150000,1,0,650
49997,2002,101,150000,1,0,1399
49998,2011,90,90000,1,0,7450
49999,2009,200,150000,1,0,6500